parameters:
    nfq.weather_class: WeatherBundle\Service\WeatherService
    nfq.open_wather_map_provider_class: WeatherBundle\Provider\OpenWeatherMapProvider
    nfq.open_wather_map_parser_class: WeatherBundle\Parser\OpenWeatherMapParser

services:
    nfq.weather:
        class: %nfq.weather_class%
        arguments: ["@nfq.open_wather_map_provider"]
    nfq.open_wather_map_provider:
        class: %nfq.open_wather_map_provider_class%
        arguments:
            - @buzz
            - @nfq.open_weather_map_parser
    nfq.open_weather_map_parser:
        class: %nfq.open_wather_map_parser_class%